export const GET_ALL_ARTISTS = 'GET_ALL_ARTISTS';
export const TOGGLE_ADD_ARTIST_DIALOG = 'TOGGLE_ADD_ARTIST_DIALOG';
export const CREATE_ARTIST = 'CREATE_ARTIST';
export const ADD_ARTIST_FAILURE = 'ADD_ARTIST_FAILURE';