export const TOGGLE_ITEM = 'TOGGLE_ITEM';
export const TOGGLE_FILE_CHANGE = 'TOGGLE_FILE_CHANGE';
export const FILE_EXTENSION_FORBIDDEN = 'FILE_EXTENSION_FORBIDDEN';
export const FILE_EXTENSION_FORBIDDEN_END = 'FILE_EXTENSION_FORBIDDEN_END';
export const ADD_AUDIO_ITEM = 'ADD_AUDIO_ITEM';
export const GET_ALL_AUDIO_ITEMS = 'GET_ALL_AUDIO_ITEMS';