export const TOGGLE_FILE_CHANGE = 'TOGGLE_FILE_CHANGE';
export const FILE_EXTENSION_FORBIDDEN = 'FILE_EXTENSION_FORBIDDEN';
export const FILE_EXTENSION_FORBIDDEN_END = 'FILE_EXTENSION_FORBIDDEN_END';
