export const TOGGLE_ITEM = 'TOGGLE_ITEM';
export const GET_ALL_AUDIO_ITEMS = 'GET_ALL_AUDIO_ITEMS';
export const LIKE_ITEM = 'LIKE_ITEM';
export const LIKE_ITEM_ARTISTS = 'LIKE_ITEM_ARTISTS';
export const TOGGLE_ITEM_ARTIST_SONGS = 'TOGGLE_ITEM_ARTIST_SONGS';
export const GET_AUDIO_ITEMS_FOR_ARTISTS = 'GET_AUDIO_ITEMS_FOR_ARTISTS';